In [2]:
import pandas as pd

In [2]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\ajoyp\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\ajoyp\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
df = pd.read_excel(r"E:\BFSI\BFSI\data\Dataset.xlsx")

In [4]:
df

,Date,URL,Source Name,Title,Opening Text,Hit Sentence,Driver,Sub driver,Sentiment,Reach
0,2026-01-17,https://www.businessworld.in/article/icici-pru...,BW BusinessWorld,ICICI Prudential Mutual Fund Launches Two Offe...,iSIF Equity Ex-Top 100 Long-Short Fund and iSI...,"... limit). Speaking at the launch, Sankaran N...",NaN,NaN,neutral,1016871.0
1,2026-03-09,https://economictimes.indiatimes.com/wealth/in...,The Economic Times,Best Fund Managers 2025: Top wealth creators w...,Indian equity fund managers navigated a challe...,... at Nippon India Asset Management Company (...,NaN,NaN,positive,NaN
2,2026-03-12,https://www.cnbctv18.com/personal-finance/icic...,CNBC-TV18,"A hybrid mutual fund has turned ₹1,000 monthly...","A ₹1,000 monthly SIP in ICICI Prudential Equit...",... returns across market cycles. Sankaran Nar...,NaN,NaN,positive,16655916.0
3,2025-10-20,https://economictimes.indiatimes.com/mf/analys...,The Economic Times,How to invest for a balanced portfolio this Di...,... 1 / 8 Financial investment this Diwali Are...,"... keep it efficient. 4 / 8 Sankaran Naren, E...",NaN,NaN,neutral,23778251.0
4,2025-07-01,https://economictimes.indiatimes.com/mf/mf-new...,The Economic Times,NFO Update: ICICI Prudential Mutual Fund launc...,ICICI Prudential launches a Nifty Private Bank...,"... , and long-term potential in banking. ICIC...",NaN,NaN,positive,62646070.0
...,...,...,...,...,...,...,...,...,...,...
95,NaT,https://play.google.com/store/apps/details?id=...,NaN,NaN,many features missing.like my transaction and ...,NaN,NaN,NaN,Negative,NaN
96,2026-01-25,https://www.fortuneindia.com/long-reads/best-i...,Fortune India,Best Investments 2026: The top-performing debt...,By preserving capital and providing predictabl...,"... Manish Banthia, chief investment officer, ...",NaN,NaN,positive,NaN
97,2025-09-22,https://economictimes.indiatimes.com/news/new-...,The Economic Times,ICICI Prudential MF’s top investment strategis...,ICICI Prudential Mutual Fund's S. Naren advise...,... ICICI Prudential Mutual Fund's S. Naren ad...,NaN,NaN,neutral,5551704.0
98,2025-09-12,https://www.reddit.com/r/StockMarketIndia/comm...,reddit.com/r/StockMarketIndia,NaN,NaN,Sometimes it just takes one bad news for marke...,NaN,NaN,neutral,NaN
99,NaT,https://play.google.com/store/apps/details?id=...,NaN,NaN,the app is pathetic. whenever the market is do...,NaN,NaN,NaN,Negative,NaN

In [20]:
import pandas as pd
import re

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

df = df.drop_duplicates(subset=["url"])

df["combined_text"] = df["title"].fillna('') + " " + df["opening_text"].fillna('')
df = df.drop_duplicates(subset=["combined_text"])

df["date"] = pd.to_datetime(df["date"], errors="coerce")

df["source_name"] = df["source_name"].astype(str).str.strip().str.lower()

if "sentiment" in df.columns:
    df["sentiment"] = df["sentiment"].astype(str).str.strip().str.capitalize()

if "reach" in df.columns:
    df["reach"] = pd.to_numeric(df["reach"], errors="coerce")

def clean_text(text):
    if pd.isna(text):
        return ""
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"[^a-zA-Z0-9₹$\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["clean_text"] = df["combined_text"].apply(clean_text)

df["processed_text"] = df["clean_text"]

final_columns = [
    "date",
    "url",
    "source_name",
    "title",
    "opening_text",
    "hit_sentence",
    "processed_text",
    "sentiment",
    "reach"
]

final_columns = [col for col in final_columns if col in df.columns]

final_df = df[final_columns]

final_df.to_csv("E:\BFSI\BFSI\data\cleaned_data.csv", index=False)

print("Data cleaning completed. File saved as cleaned_data.csv")

Data cleaning completed. File saved as cleaned_data.csv

<>:50: SyntaxWarning: invalid escape sequence '\B'
<>:50: SyntaxWarning: invalid escape sequence '\B'
C:\Users\ajoyp\AppData\Local\Temp\ipykernel_6572\161871670.py:50: SyntaxWarning: invalid escape sequence '\B'
  final_df.to_csv("E:\BFSI\BFSI\data\cleaned_data.csv", index=False)

In [4]:
new_df = pd.read_csv("E:\BFSI\BFSI\data\cleaned_data.csv")

<>:1: SyntaxWarning: invalid escape sequence '\B'
<>:1: SyntaxWarning: invalid escape sequence '\B'
C:\Users\ajoyp\AppData\Local\Temp\ipykernel_14200\3783608571.py:1: SyntaxWarning: invalid escape sequence '\B'
  new_df = pd.read_csv("E:\BFSI\BFSI\data\cleaned_data.csv")

In [5]:
new_df

,date,url,source_name,title,opening_text,hit_sentence,processed_text,sentiment,reach
0,2026-01-17,https://www.businessworld.in/article/icici-pru...,bw businessworld,ICICI Prudential Mutual Fund Launches Two Offe...,iSIF Equity Ex-Top 100 Long-Short Fund and iSI...,"... limit). Speaking at the launch, Sankaran N...",icici prudential mutual fund launches two offe...,Neutral,1016871.0
1,2026-03-09,https://economictimes.indiatimes.com/wealth/in...,the economic times,Best Fund Managers 2025: Top wealth creators w...,Indian equity fund managers navigated a challe...,... at Nippon India Asset Management Company (...,best fund managers 2025 top wealth creators wh...,Positive,NaN
2,2026-03-12,https://www.cnbctv18.com/personal-finance/icic...,cnbc-tv18,"A hybrid mutual fund has turned ₹1,000 monthly...","A ₹1,000 monthly SIP in ICICI Prudential Equit...",... returns across market cycles. Sankaran Nar...,a hybrid mutual fund has turned ₹1000 monthly ...,Positive,16655916.0
3,2025-10-20,https://economictimes.indiatimes.com/mf/analys...,the economic times,How to invest for a balanced portfolio this Di...,... 1 / 8 Financial investment this Diwali Are...,"... keep it efficient. 4 / 8 Sankaran Naren, E...",how to invest for a balanced portfolio this di...,Neutral,23778251.0
4,2025-07-01,https://economictimes.indiatimes.com/mf/mf-new...,the economic times,NFO Update: ICICI Prudential Mutual Fund launc...,ICICI Prudential launches a Nifty Private Bank...,"... , and long-term potential in banking. ICIC...",nfo update icici prudential mutual fund launch...,Positive,62646070.0
...,...,...,...,...,...,...,...,...,...
78,2025-11-03,https://obnews.co/Index/flowNewsDetail/id/1262...,obnews,Experts Predict Long-Term Shine in Silver: ICI...,Despite the recent correction in silver prices...,"... Use Chintan Haria, Principal – Investment ...",experts predict longterm shine in silver icici...,Positive,2555786.0
79,2025-08-12,https://www.angelone.in/news/mutual-funds/3-be...,angel one,3 Best Performing Large Cap Mutual Funds with ...,Discover the top 3 large-cap mutual funds deli...,NaN,3 best performing large cap mutual funds with ...,Positive,5814639.0
80,2025-07-08,https://www.zeebiz.com/personal-finance/mutual...,zee business,ICICI Prudential Active Momentum NFO opens: Mi...,The momentum fund is an open-ended equity sche...,"... Naren, Executive Director and Chief Invest...",icici prudential active momentum nfo opens min...,Neutral,259919.0
81,2026-01-25,https://www.fortuneindia.com/long-reads/best-i...,fortune india,Best Investments 2026: The top-performing debt...,By preserving capital and providing predictabl...,"... Manish Banthia, chief investment officer, ...",best investments 2026 the topperforming debt f...,Positive,NaN
82,2025-09-22,https://economictimes.indiatimes.com/news/new-...,the economic times,ICICI Prudential MF’s top investment strategis...,ICICI Prudential Mutual Fund's S. Naren advise...,... ICICI Prudential Mutual Fund's S. Naren ad...,icici prudential mfs top investment strategist...,Neutral,5551704.0